static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT]={
	"No Playstation 2 memory cards detected.",
	"Memory Cards were detected\nin both slot 1 and 2.\n\nSelect the target memory card.",
	"FMCB will be installed onto\nthe memory card in slot 1. Continue?",
	"FMCB will be installed onto\nthe memory card in slot 2. Continue?",
	"FHDB will be installed onto\nthe Harddisk Drive. Continue?",
	"Select installation type:",
	"Cache initialization failed.",
	"Existing FMCB CNF found!\nDo you want to keep it?",
	"Existing FHDB CNF found!\nDo you want to keep it?",
	"Cleanup failed.",
	"The installation was\ncleaned up successfully.",
	"Installation failed.",
	"Installation completed.",
	"FMCB on the memory card in\nslot 1 will be cleaned up. Continue?",
	"FMCB on the memory card in\nslot 2 will be cleaned up. Continue?",
	"FHDB on the Harddisk Drive\nwill be cleaned up. Continue?",
	"The memory card in slot 1 will be\nformatted.\n\nContinue?",
	"The memory card in slot 2 will be\nformatted.\n\nContinue?",
	"Format failed to complete.",
	"Format complete.",
	"The memory card in slot 1 will be\ndumped.\n\nContinue?",
	"The memory card in slot 2 will be\ndumped.\n\nContinue?",
	"Memory card dumping failed.",
	"Memory card dumped.",
	"The memory card in slot 1 will be\nrestored.\n\nContinue?",
	"The memory card in slot 2 will be\nrestored.\n\nContinue?",
	"Memory card restoration failed.",
	"Memory card restored.",
	"Multi-installation required,\nbut not found on card.",
	"Multi-installation detected!\nPlease uninstall first.",
	"Failed to calculate free space on card.",
	"Insufficient free space on card.",
	"Insufficient free space on\nthe HardDisk Drive.",
	"Insufficient free space on\nin the APPS partition.",
	"Formatting memory card.\n\nPlease do not switch off the power\nor remove the card.",
	"Cleaning up memory card.\n\nPlease do not switch off the power\nor remove the card.",
	"Uninstalling FHDB.\n\nPlease do not switch off the power\nor disconnect the HDD unit.",
	"Read error.\nPlease check your installation media.",
	"Write error.\nPlease check your memory card.",
	"Read error.\nPlease check your memory card.",
	"Write error.\nPlease check your Harddisk Drive.",
	"Write error.\nPlease check your installation media.",
	"Out of memory.",
	"File not found.\nPlease check your installation media.",
	"Stop dumping memory card?",
	"Stop restoring memory card?",
	"Failed to create crosslinked files.",
	"Failed to bind MagicGate file to\nMemory Card.",
	"Can't remove multi-installation\nmade by an incompatible installer.",
	"Install FMCB for this console.",
	"Install FMCB for all consoles.",
	"Uninstall FMCB.",
	"Downgrade a multi-installation to a\nnormal installation.",
	"Format memory card.",
	"Dump memory card contents to file.",
	"Flash memory card contents from file.",
	"Install FMCB (PSX) on this memory card.",
	"Install FHDB for this console.",
	"Uninstall FHDB.",
	"Exit program.",
	"The HardDisk Drive (HDD) unit has a problem.\nPlease run a disk check first.",
	"S.M.A.R.T. has reported that the\nHardDisk Drive (HDD) unit has failed.\n\nThe HDD unit must be replaced.",
	"This console does not support FMCB.\n\nHowever, you can still make\ninstallations with it.",
	"While the multi-installation allows\nyou to create a FMCB card that\ncan boot on all PlayStation 2 consoles\nwith the least space requirements,\nit goes against the design of the\nMemory Card by introducing controlled\nfilesystem corruption.\n\nIt is hence strongly recommended to\ncreate a normal installation instead.",
	"Quit program?",
};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT]={
	"OK",
	"Cancel",
	"Yes",
	"No",
	"Warning",
	"Error",
	"Information",
	"Confirmation",
	"Slot 1",
	"Slot 2",
	"Memory Card",
	"HDD",
	"Please wait",
	"Now installing...",
	"Now dumping...",
	"Now restoring...",
	"Normal",
	"Cross-model",
	"Cross-regional",
	"Rate:",
	"Time\nremaining:",
	"Install",
	"Multi-install",
	"Uninstall FMCB",
	"Uninstall MI",
	"Format MC",
	"Dump MC",
	"Restore MC",
	"Install FMCB (PSX)",
	"Install FHDB",
	"Uninstall FHDB",
	"Exit",
	"B",
	"KB",
	"MB",
	"GB",
	"TB",
	"B/s",
	"KB/s",
	"MB/s",
	"Available space:",
	"Required space:",
	"Main Menu",
	"Extras Menu",
	"Memory Card Menu",
};
